# Generated by Django 3.1.1 on 2020-10-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('MO', '아침'), ('LU', '점심'), ('DI', '저녁'), ('SN', '간식기타')], default='MO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('carbohydrate', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('diet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.diet')),
            ],
        ),
    ]
